name: Check wasm build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Clippy
      run: cargo clippy --target=wasm32-unknown-unknown -praven-gui
    - name: Build
      run: cargo build --target=wasm32-unknown-unknown -praven-gui

