name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  check:
    strategy:
      matrix:
        target: [
          "ubuntu-24.04-arm",
          "ubuntu-latest",
          "windows-latest",
          "macos-14",
        ]
    runs-on: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - if: runner.os == 'Linux'
      name: Install dependencies
      run: sudo apt install libasound2-dev
      shell: bash
    - name: Clippy
      run: cargo clippy --all-targets --verbose
    - name: Test
      run: cargo test --verbose

